version: '3'

services:
  app:
    image: gui-container:latest
    build: .
    volumes:
      - ..:/workspace:cached
    network_mode: host
    privileged: true
    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    entrypoint: /entrypoint.sh
